### ISSUE TITLE
Livewire 3

### ISSUE THREAD

**Issue by codebyray** [rw4lll/livewire-devtools#17]
Any plans to update this so it will recognize Livewire 3?

**Comment by rw4lll** [comment]
> Any plans to update this so it will recognize Livewire 3?

I'm thinking about possible updating this tool to support v3, but not sure about the approach.
We could just update existing codebase to support v3 with minor updates, but its very old and it will be more and more difficult to support in the future. This is one of the reasons, why I stopped my current roadmap. On the other side, rebuilding this stuff from scratch is a lot of work and take much more time. What do you think would be better? Quick and dirty update or brand new product?

**Comment by codebyray** [comment]
I would start with the quick and dirty update. Start a dev branch for the rewrite version and slowly convert to a new codebase.

Lots of developers will be moving to v3 of Livewire and will want to use this tool.
