### ISSUE TITLE
Livewire V3: Events not captured

### ISSUE THREAD

**Issue by kassah** [rw4lll/livewire-devtools#19]
We are not seeing events captured when using this with Livewire V3.

Will try to add a minimal repro case later in case you cannot reproduce easily.

**Comment by rw4lll** [comment]
@kassah yeah, some example would be appreciated.

**Comment by jcordingley** [comment]
I also am experiencing this issue, any event dispatched from a livewire component is not shown in the event view

**Comment by rw4lll** [comment]
@kassah @jcordingley should be fixed in v1.1.1
